In [1]:
import numpy as np
from gsd_capacity_investment import compute_cutoffs, compute_ccps, compute_ex_ante_value


### Example 1 from GSD (2025)

In [2]:
costs = np.array([1, 2, 3])
cs_values = np.array([0, 1.5, 2])

In [3]:
cutoffs = compute_cutoffs(cs_values, costs)
cutoffs

(array([inf, 1.5, 0.5]),
 array([ 1.5,  0.5, -inf]),
 array([False, False, False]))

In [4]:
ccps = compute_ccps(*cutoffs)
ccps

array([0.0668072 , 0.24173034, 0.69146246])

In [5]:
value = compute_ex_ante_value(cs_values, costs, *cutoffs)
value

np.float64(2.227103351163911)

### Example 2 from GSD (2025)

In [6]:
costs = np.array([1, 2, 3])
cs_values = np.array([0, 0.5, 2])

In [7]:
cutoffs = compute_cutoffs(cs_values, costs)
cutoffs

(array([inf, 0.5, 1. ]),
 array([ 1. ,  1.5, -inf]),
 array([False,  True, False]))

In [8]:
ccps = compute_ccps(*cutoffs)
ccps

array([0.15865525, 0.        , 0.84134475])

In [9]:
value = compute_ex_ante_value(cs_values, costs, *cutoffs)
value

np.float64(2.166630941175373)

### Example 3 with larger action set

In [10]:
# Set random seed
np.random.seed(321)

# Sample random choice-specific values
cs_values = np.random.normal(size=20)
print("Choice-specific values: ", cs_values)

# Sample and and sort costs
costs = np.random.normal(size=20)
costs = np.sort(costs)
print("Costs: ", costs)

Choice-specific values:  [ 0.17251947  1.63548253  0.0373364  -0.88414969 -1.14319226 -0.62136604
 -1.34864958 -0.81973103 -0.1342539   1.59960004 -0.28360363 -0.50633982
  0.06890842  1.4522595  -1.63909561 -0.31265944 -0.87126643 -0.4566824
 -0.12246672 -0.45106231]
Costs:  [-2.04378667 -1.36217968 -1.09228374 -1.03032386 -0.88906098 -0.73763812
 -0.43200605 -0.34120143 -0.30189941 -0.16598697 -0.13850416 -0.01855969
  0.3641818   0.37483657  0.41227425  0.43338068  0.64538909  0.81507352
  1.03147165  1.35830044]


In [11]:
cutoffs = compute_cutoffs(cs_values, costs)
cutoffs

(array([            inf,  2.14634397e+00, -5.92134185e+00, -1.48723041e+01,
        -5.87310290e+00, -3.61360830e+00, -3.20814527e+00, -2.40476579e+00,
        -1.66912135e+00, -2.99972479e-02, -6.85229796e+01, -1.42846013e+01,
        -2.88717801e+00, -2.72437363e-01, -8.25733444e+01, -3.01468232e+01,
        -8.58807724e+00, -4.33616915e+00, -2.39817559e+00, -1.93532459e+00]),
 array([ 2.14634397e+00, -2.99972479e-02, -5.80903776e+00, -1.83376247e+00,
         3.44615203e+00, -2.37960486e+00,  5.82479741e+00,  1.74412703e+01,
         1.27571395e+01, -2.72437363e-01, -1.85699417e+00,  1.50296805e+00,
         1.29834050e+02, -1.93532459e+00,  6.28451446e+01, -2.63483411e+00,
         2.44326493e+00,  1.54444807e+00, -1.00540587e+00,            -inf]),
 array([False, False,  True,  True,  True,  True,  True,  True,  True,
        False,  True,  True,  True, False,  True,  True,  True,  True,
         True, False]))

In [12]:
ccps = compute_ccps(*cutoffs)
ccps

array([0.01592277, 0.4960426 , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.09539175,
       0.        , 0.        , 0.        , 0.36616764, 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.02647524])

In [13]:
value = compute_ex_ante_value(cs_values, costs, *cutoffs)
value

np.float64(2.25880176395387)